[tool.poetry]
name = "phone-number-validator"
version = "0.1.0"
description = ""
authors = ["flavien-hugs <flavienhugs@pm.me>"]
readme = "README.md"
packages = [{include = "src", from = "src"}]

[tool.poetry.dependencies]
python = "^3.12"
httpx = "^0.27.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
